# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'curl https://cdn.shiftleft.io/download/installer-dotnet-framework-latest-windows-x64.zip -OutFile installer-dotnet-framework-latest-windows-x64.zip'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir d:/a/1/s'
    